name: Deploy to ECR
# updated secrets
on: 
  push:
    branches: development

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1
        
    - name: Build and push MySQL Docker image
        run:|
          docker build -t my_db -f Dockerfile_mysql .
          docker tag my_db:latest <your-ecr-repository-url>/my_db:latest
          docker push <your-ecr-repository-url>/my_db:latest

    - name: Build and push application Docker image
        run:|
          docker build -t my_app -f Dockerfile .
          docker tag my_app:latest <your-ecr-repository-url>/my_app:latest
          docker push <your-ecr-repository-url>/my_app:latest
